t=0:0.001:2;
wc=100*pi;
wm=2*pi;
Ac=1;
Am=1;
m=Am*cos(wm.*t);
c=Ac*cos(wc.*t);
k1=0.5;
k2=1;
k3=2;
S1=Ac*(1+k1.*m).*cos(wc.*t);
S2=Ac*(1+k2.*m).*cos(wc.*t);
S3=Ac*(1+k3.*m).*cos(wc.*t);
subplot(5,1,1);
plot(t,m);
title('Message Signal');
xlabel('t');
ylabel('m(t)');
subplot(5,1,2);
plot(t,c);
title('Carrier Signal');
xlabel('t');
ylabel('c(t)');
subplot(5,1,3);
plot(t,S1);
title('AM Undermodulated Signal[Modulation for k1=0.5]');
xlabel('t');
ylabel('S1(t)');
subplot(5,1,4);
plot(t,S2);
title('AM Normalmodulated Signal[Modulation for k2=1]');
xlabel('t');
ylabel('S2(t)');
subplot(5,1,5);
plot(t,S3);
title('AM Overmodulated Signal[Modulation for k3=2]');
xlabel('t');
ylabel('S3(t)');