n=0:59;
p=2;
q=3;
x = exp(-n/15).*sin((2*n*pi)/13+ pi/3);
yi=interp(x,p);
y2=decimate(y1,q);
y3=resample(x,p,q);
subplot (4,1,1);
stem (n,x);
title('Given Signal');
xlabel('n');
ylabel('Amplitude');
subplot (4,1,2);
stem(0:119,y1);
title('Interpolation');
xlabel('n');
ylabel('Amplitude');
subplot (4,1,3);
stem(0:39,y2);
title('Decimation');
xlabel('n');
ylabel('Amplitude');
subplot (4,1,4);
stem(0:39,y3);
title('Resampled');
xlabel('n');
ylabel('Amplitude');