n=0:1:2;
y=[1 3 2];
x=[1 0 3];
w=-2*pi:(2*pi)/100:2*pi;
b=exp(-1i).^(n'*w);
x=x*b;
y=y*b;
h=y./x;
subplot(2,1,1);
plot(w,abs(h));
title('magnitude plot of frequency response by using differential equation');
xlabel('\omega');
ylabel('abs(h)');
subplot(2,1,2);
plot(w,angle(h));
title('phase plot of frequency response by using differential equation');
xlabel('\omega');
ylabel('angle(h)');
