t=0:0.1:20;
y=square(t);
y1=square(t-1);
y2=square(3*t);
y3=square(-t);
subplot(4,1,1);
plot(t,y);
xlabel('t');
ylabel('x(t)');
title('square signal')
axis([0 20 -2 2]);
subplot(4,1,2);
plot(t,y1);
xlabel('t');
ylabel('x1(t)');
title('time shifting of square signal');
axis([0 20 -2 2]);
subplot(4,1,3);
plot(t,y2);
xlabel('t');
ylabel('x2(t)');
title('time scaling of square signal');
axis([0 20 -2 2]);
subplot(4,1,4);
plot(t,y3);
xlabel('t');
ylabel('x3(t)');
title('reflection of square signal')
axis([0 20 -2 2]);

t=0:0.1:20;
y=sawtooth(t);
y1=sawtooth(t-3);
y2=sawtooth(3*t);
y3=sawtooth(-t);
subplot(4,1,1);
plot(t,y);
xlabel('t');
ylabel('x(t)');
title('triangular signal')
axis([0 20 -2 2]);
subplot(4,1,2);
plot(t,y1);
xlabel('t');
ylabel('x1(t)');
title('time shifting of triangular signal');
axis([0 20 -2 2]);
subplot(4,1,3);
plot(t,y2);
xlabel('t');
ylabel('x2(t)');
title('time scaling of sawtooth signal');
axis([0 20 -2 2]);
subplot(4,1,4);
plot(t,y3);
xlabel('t');
ylabel('x3(t)');
title('reflection of sawtooth signal')
axis([0 20 -2 2]);

t=0:0.1:20;
y=sin(t);
y1=sin(t-1);
y2=sin(3*t);
y3=sin(-t);
subplot(4,1,1);
plot(t,y);
xlabel('t');
ylabel('x(t)');
title('sinusoidal signal')
axis([0 20 -2 2]);
subplot(4,1,2);
plot(t,y1);
xlabel('t');
ylabel('x1(t)');
title('time shifting of sinusoidal signal');
axis([0 20 -2 2]);
subplot(4,1,3);
plot(t,y2);
xlabel('t');
ylabel('x2(t)');
title('time scaling of sinusoidal signal');
axis([0 20 -2 2]);
subplot(4,1,4);
plot(t,y3);
xlabel('t');
ylabel('x3(t)');
title('reflection of sinusoidal signal')
axis([0 20 -2 2]);

t=0:0.1:20;
y=t;
y1=(t-3);
y2=(3*t);
y3=(-t);
subplot(4,1,1);
plot(t,y);
xlabel('t');
ylabel('x(t)');
title('ramp signal')
axis([0 25 -20 20]);
subplot(4,1,2);
plot(t,y1);
xlabel('t');
ylabel('x1(t)');
title('time shifting of ramp signal');
axis([0 25 -20 20]);
subplot(4,1,3);
plot(t,y2);
xlabel('t');
ylabel('x2(t)');
title('time scaling of ramp signal');
axis([0 25 -20 20]);
subplot(4,1,4);
plot(t,y3);
xlabel('t');
ylabel('x3(t)');
title('reflection of ramp signal')
axis([0 25 -20 20]);

t=0:0.1:20;
y=exp(t);
y1=exp(t-1);
y2=exp(3*t);
y3=exp(-t);
subplot(4,1,1);
plot(t,y);
xlabel('t');
ylabel('x(t)');
title('exponential signal')
axis([0 20 -2 2]);
subplot(4,1,2);
plot(t,y1);
xlabel('t');
ylabel('x1(t)');
title('time shifting of exponential signal');
axis([0 20 -2 2]);
subplot(4,1,3);
plot(t,y2);
xlabel('t');
ylabel('x2(t)');
title('time scaling of exponential signal');
axis([0 20 -2 2]);
subplot(4,1,4);
plot(t,y3);
xlabel('t');
ylabel('x3(t)');
title('reflection of exponential signal')
axis([0 20 -2 2]);

t=0:0.1:20;
y=sign(t);
y1=1;
y2=(1+sign(t))*0.5;
y3=(1+sign(t-5))*0.5;
y4=(1+sign(3*t))*0.5;
y5=(1+sign(-t))*0.5;
subplot(4,1,1);
plot(t,y2);
xlabel('t');
ylabel('x(t)');
title('step signal')
axis([0 20 -1.5 1.5]);
subplot(4,1,2);
plot(t,y3);
xlabel('t');
ylabel('x1(t)');
title('time shifting of step signal');
axis([0 20 -1.5 1.5]);
subplot(4,1,3);
plot(t,y4);
xlabel('t');
ylabel('x2(t)');
title('time scaling of step signal');
axis([0 20 -1.5 1.5]);
subplot(4,1,4);
plot(t,y5);
xlabel('t');
ylabel('x3(t)');
title('reflection of step signal')
axis([0 20 -1.5 1.5]);

t=-20:0.01:20;
y1=0.5*(1+sign(t)-sign(t-0.01));
y2=0.5*(1+sign(t-2)-sign((t-2)-0.01));
y3=0.5*(1+sign(2*t)-sign(2*t-0.01));
y4=0.5*(1+sign(-t)-sign(-t-0.01));
subplot(4,1,1);
plot(t,y1);
xlabel('t');
ylabel('x(t)');
title('impulse waveform');
axis([-9 9 0 2]);
subplot(4,1,2);
plot(t,y2);
xlabel('t');
ylabel('x1(t)');
title('time shifting of impulse waveform');
axis([-9 9 0 2]);
subplot(4,1,3);
plot(t,y3);
xlabel('t');
ylabel('x2(t)');
title('time scaling of impulse waveform');
axis([-9 9 0 2]);
subplot(4,1,4);
plot(t,y4);
xlabel('t');
ylabel('x3(t)');
title('reflection of impulse waveform');
axis([-9 9 0 2]);
